import Mathlib

/-!
# Challenge: Collatz Conjecture

Field: Number Theory
Difficulty: very-hard
Formalization: formalized

For any positive integer n, the sequence n → n/2 (if even) or 3n+1 (if odd) eventually reaches 1.


Generated by: autolean challenge collatz
-/

-- Main conjecture
def collatz_step (n : Nat) : Nat :=
  if n % 2 == 0 then n / 2 else 3 * n + 1

def collatz_reaches_one (n : Nat) : Prop :=
  ∃ k : Nat, (Nat.iterate collatz_step k n) = 1

theorem collatz_conjecture (n : Nat) (hn : n > 0) :
    collatz_reaches_one n := by
  sorry

-- Sub-results (more likely to be provable)

-- Sub-result 1
theorem collatz_step_one : collatz_step 1 = 4 := by rfl

-- Sub-result 2
theorem collatz_step_two : collatz_step 2 = 1 := by rfl

-- Sub-result 3
theorem collatz_reaches_one_of_pow2 (k : Nat) : collatz_reaches_one (2^k) := by refine ⟨k, ?_⟩
                                                                                induction k with
                                                                                | zero =>
                                                                                  first
                                                                                    | rfl
                                                                                    | simp
                                                                                    | norm_num
                                                                                | succ n ih =>
                                                                                  have h2 : (2 : ℕ) ^ (n + 1) % 2 = 0 := by
                                                                                    rw [pow_succ]; omega
                                                                                  have hd : (2 : ℕ) ^ (n + 1) / 2 = 2 ^ n := by
                                                                                    rw [pow_succ]; omega
                                                                                  rw [Function.iterate_succ_apply]
                                                                                  first
                                                                                    | (have hc : collatz (2 ^ (n + 1)) = 2 ^ n := by
                                                                                         simp [collatz, h2, hd, Nat.even_pow]
                                                                                       rw [hc]
                                                                                       exact ih)
                                                                                    | (have hc : collatz_step (2 ^ (n + 1)) = 2 ^ n := by
                                                                                         simp [collatz_step, h2, hd, Nat.even_pow]
                                                                                       rw [hc]
                                                                                       exact ih)
                                                                                    | simpa [h2, hd, Nat.even_pow] using ih
                                                                                    | simp_all [h2, hd, Nat.even_pow]

-- References
-- https://en.wikipedia.org/wiki/Collatz_conjecture