import Mathlib

/-!
# Challenge: Twin Prime Conjecture

Field: Number Theory
Difficulty: very-hard
Formalization: formalized

There are infinitely many pairs of primes (p, p+2).


Generated by: autolean challenge twin-primes
-/

-- Main conjecture
def IsTwinPrime (p : Nat) : Prop :=
  Nat.Prime p ∧ Nat.Prime (p + 2)

theorem twin_prime_conjecture :
    ∀ N : Nat, ∃ p : Nat, p > N ∧ IsTwinPrime p := by
  sorry

-- Sub-results (more likely to be provable)

-- Sub-result 1
theorem twin_prime_3 : IsTwinPrime 3 := by trivial

-- Sub-result 2
theorem twin_prime_5 : IsTwinPrime 5 := by trivial

-- Sub-result 3
theorem twin_prime_11 : IsTwinPrime 11 := by sorry

-- References
-- https://en.wikipedia.org/wiki/Twin_prime