-- User theorems (auto-generated by autolean prove)

import Mathlib.Data.List.Basic

theorem list_reverse_append (α : Type _) (as bs : List α) :
  List.reverse (as ++ bs) = List.reverse bs ++ List.reverse as := by
  rw [List.reverse_append]
