-- User theorems (auto-generated by autolean prove)

import Mathlib.Data.List.Basic

theorem list_reverse_append {α : Type} (as bs : List α) :
  List.reverse (as ++ bs) = List.reverse bs ++ List.reverse as := by
  sorry
