"""Provider-neutral model interfaces and the backend registry."""

from autolean.llm.base import (
    DEFAULT_MAX_OUTPUT_TOKENS,
    DEFAULT_TEMPERATURE,
    DEFAULT_TIMEOUT,
    BaseBackend,
    Capabilities,
    DocumentBackend,
    DocumentInput,
    GenerateFn,
    InferenceLocation,
    LLMAuthenticationError,
    LLMBackend,
    LLMConfig,
    LLMError,
    LLMRateLimitError,
    LLMRefusalError,
    LLMResponse,
    LLMTransientError,
    ModelCallReceipt,
    validate_endpoint,
)
from autolean.llm.registry import (
    BACKEND_NAMES,
    BACKENDS,
    PROVIDER_NAMES,
    BackendSpec,
    create_llm_client,
    endpoint_location,
    inference_location,
    provider_name,
    resolve_backend_name,
    validate_backend_config,
)

__all__ = [
    "BACKENDS",
    "BACKEND_NAMES",
    "DEFAULT_MAX_OUTPUT_TOKENS",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_TIMEOUT",
    "PROVIDER_NAMES",
    "BackendSpec",
    "BaseBackend",
    "Capabilities",
    "DocumentBackend",
    "DocumentInput",
    "GenerateFn",
    "InferenceLocation",
    "LLMAuthenticationError",
    "LLMBackend",
    "LLMConfig",
    "LLMError",
    "LLMRateLimitError",
    "LLMRefusalError",
    "LLMResponse",
    "LLMTransientError",
    "ModelCallReceipt",
    "create_llm_client",
    "endpoint_location",
    "inference_location",
    "provider_name",
    "resolve_backend_name",
    "validate_backend_config",
    "validate_endpoint",
]
