"""Library builder — create missing types, structures, and lemmas.

When mathlib doesn't have what you need, AutoLean can build it.
Two modes:
  1. Proactive: `autolean build-library "differential geometry"` — creates
     definitions and basic lemmas for a topic
  2. Reactive: During proving, when a proof fails with "unknown identifier",
     the agent tries to define the missing piece and retries

All generation uses the LOCAL LLM (the same Ollama model the agent already
runs for proof generation — e.g., gemma4:26b at localhost:11434).
No external LLM APIs are called. The only external network calls are to
Loogle and LeanSearch, which are database lookups, not LLM inference.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

from rich.console import Console

console = Console()
log = logging.getLogger("autolean")

# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------

BUILD_LIBRARY_PROMPT = """\
You are a Lean 4 formalization expert building a library for {topic}.

Create a .lean file with:
1. Necessary imports from Mathlib (as comments if unsure they exist)
2. Core definitions (structures, types, typeclasses)
3. Basic lemmas with sorry proofs (the agent will fill these later)
4. Docstrings explaining each definition

Focus on foundational definitions that would be needed to state and prove
theorems in {topic}. Keep it self-contained and well-organized.

Output ONLY valid Lean 4 code. No markdown fences.
"""

FILL_GAP_PROMPT = """\
A proof attempt failed because Lean could not find: {missing_name}

The error was: {error_message}

Based on the context:
```lean
{context}
```

Create a Lean 4 definition or lemma for `{missing_name}` that would
make the proof work. Output ONLY the Lean 4 definition. No markdown.
"""


# ---------------------------------------------------------------------------
# Gap detection
# ---------------------------------------------------------------------------


@dataclass
class MissingDefinition:
    """A definition that's needed but doesn't exist."""

    name: str
    error_message: str
    context: str  # surrounding code where it was needed
    file: str


def detect_missing_definitions(error_message: str, context: str = "", file: str = "") -> list[MissingDefinition]:
    """Parse build errors to find missing identifiers/definitions.

    Detects:
    - "unknown identifier 'Foo'"
    - "unknown constant 'Bar.baz'"
    - "failed to synthesize instance Foo Bar"
    """
    gaps: list[MissingDefinition] = []

    # Unknown identifier
    for m in re.finditer(r"unknown (?:identifier|constant) ['\u2018](\S+?)['\u2019]", error_message):
        name = m.group(1)
        # Skip names that are likely typos of standard things
        if len(name) < 2 or name.startswith("_"):
            continue
        gaps.append(MissingDefinition(
            name=name, error_message=error_message[:200],
            context=context, file=file,
        ))

    # Failed to synthesize instance
    for m in re.finditer(r"failed to synthesize\s+(?:instance\s+)?(\S+)", error_message):
        name = m.group(1)
        gaps.append(MissingDefinition(
            name=name, error_message=error_message[:200],
            context=context, file=file,
        ))

    return gaps


# ---------------------------------------------------------------------------
# Library file generation
# ---------------------------------------------------------------------------


def generate_library_file(
    topic: str,
    output_path: Path,
    llm_generate: object,
) -> Path:
    """Generate a Lean 4 library file for a mathematical topic.

    Args:
        topic: Mathematical topic (e.g., "differential geometry", "graph theory")
        output_path: Where to write the .lean file
        llm_generate: LLM generate function

    Returns:
        Path to the generated file.
    """
    prompt = BUILD_LIBRARY_PROMPT.format(topic=topic)
    response = llm_generate("You are a Lean 4 formalization expert.", prompt)

    code = response.text.strip()
    # Clean markdown fences
    code = re.sub(r"^```(?:lean4?|)\s*\n?", "", code)
    code = re.sub(r"\n?```\s*$", "", code)

    # Add header
    header = (
        f"/-!\n"
        f"# {topic.title()} Library\n"
        f"\n"
        f"Auto-generated by AutoLean build-library.\n"
        f"Fill sorry targets with: uv run autolean run\n"
        f"-/\n\n"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header + code + "\n", encoding="utf-8")

    log.info("Generated library file for '%s': %s", topic, output_path)
    return output_path


def fill_gap(
    gap: MissingDefinition,
    lean_file: Path,
    llm_generate: object,
) -> str | None:
    """Try to define a missing identifier using the LLM.

    Returns the Lean 4 definition code, or None if it couldn't generate one.
    """
    prompt = FILL_GAP_PROMPT.format(
        missing_name=gap.name,
        error_message=gap.error_message,
        context=gap.context[:2000],
    )

    response = llm_generate(
        "You are a Lean 4 expert. Create minimal, correct definitions.",
        prompt,
    )

    code = response.text.strip()
    # Clean markdown
    code = re.sub(r"^```(?:lean4?|)\s*\n?", "", code)
    code = re.sub(r"\n?```\s*$", "", code)

    if not code or len(code) < 5:
        return None

    log.info("Generated definition for '%s': %d chars", gap.name, len(code))
    return code
